sudo: false
dist: trusty
language: c
compiler:
  - musl-gcc
os:
  - linux

addons:
  apt:
    packages:
      - jq
      - build-essential
      - pkg-config
      - ninja-build
      - wget
      - ca-certificates
      - musl-tools
      - python3
      - python3-pip

install:
  - pip3 install --user meson

script:
  - ./do.sh
