version: 2
jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run: ./deps.sh
      - run: ./do.sh
      - run: tar cJvf kafkacat.txz build/kafkacat build/kafkacat-LICENSES.txt
      - store_artifacts:
          path: kafkacat.txz
          destination: kafkacat.txz

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+-\d+$/
