version: 2
jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run: ./deps.sh
      - run: ./do.sh
      - run: tar cJvf kafkacat.txz build/kafkacat kafkacat-LICENSES.txt
      - store_artifacts:
          path: kafkacat.txz
          destination: kafkacat.txz
